### ISSUE TITLE
Leider keine automatische Installation des Add on

### ISSUE THREAD

**Issue by benzoesaeure** [mak-gitdev/HA_enoceanmqtt#106]
### The problem

Hallo, leider bekomme ich immer bei der Installation des Add on  folgenden Fehler: Was kann ich machen?

 The command '/bin/ash -o pipefail -c apk add --no-cache python3 py3-pip git && python3 -m pip install --upgrade pip && pip3 install pyyaml && pip3 install tinydb && pip3 install git+https://github.com/mak-gitdev/enocean.git && git clone https://github.com/embyt/enocean-mqtt.git && cd enocean-mqtt && python3 setup.py develop && cd .. && if [ "${BUILD_VERSION}" = "head" ]; then echo "Installing from repository head" && git clone -b develop --single-branch --depth 1 https://github.com/mak-gitdev/HA_enoceanmqtt.git ; else if [ -z "${BUILD_VERSION##*.*.*}" ]; then echo "Installing development version ${BUILD_VERSION%-*}" ; else echo "Installing stable version ${BUILD_VERSION%-*}" ; fi; wget -nv -O "/app.tar.gz" "https://github.com/mak-gitdev/HA_enoceanmqtt/archive/refs/tags/${BUILD_VERSION%-*}.tar.gz" && echo "Extracting /app.tar.gz" && tar xzf "/app.tar.gz" && rm "/app.tar.gz" && mv -v "HA_enoceanmqtt-${BUILD_VERSION%-*}" HA_enoceanmqtt ; fi; cp -rf HA_enoceanmqtt/enoceanmqtt enocean-mqtt && rm -rf HA_enoceanmqtt' returned a non-zero code: 1

### What type of installation are you running?

Addon

### What version of HA_enoceanmqtt has the issue?

0.1.28

### What type of Home Assitant installation are you running?

Home Assistant OS

**Comment by mak-gitdev** [comment]
Hi @benzoesaeure,

I just released a new version of the addon (0.1.28-1) which should fix this issue.
Please close the issue if that version effectively fixes this issue.

Otherwise, please let me know what error you get if any.

**Comment by benzoesaeure** [comment]
Thank you very much for the quick support. The instalation is runing
