### ISSUE TITLE
Installation fails "The command '/bin/ash -o pipefail........returned a non-zero code: 1"

### ISSUE THREAD

**Issue by Exezz78** [mak-gitdev/HA_enoceanmqtt#113]
### The problem

After clicking on "Install" in Home Assistant Add-On store, attached error message is showing.
![image](https://github.com/mak-gitdev/HA_enoceanmqtt/assets/64520024/2be6ffab-e8f3-4c42-8137-5554c456a76d)

### What type of installation are you running?

Standalone

### What version of HA_enoceanmqtt has the issue?

0.1.28-1

### What type of Home Assitant installation are you running?

Home Assistant OS

**Comment by mak-gitdev** [comment]
Hi @Exezz78, 

I haven't been able to reproduce this issue.
What is your hardware running your HA instance ?

**Comment by Exezz78** [comment]
Hi @mak-gitdev, 

thanks a lot for looking into this. In fact I have 2 HA running (PRD and UAT). On my PRD machine, the add-on installed without issues (last week).
On the UAT machine, I encountered the shared issue. Machine is a Raspberry Pi4 (4 GB) with a HA freshly installed only for testing of EnOcean purposes (via USB300).

Thanks again!
Exezz

**Comment by mak-gitdev** [comment]
@Exezz78,

Have an RPi4 4GB and still can't reproduce the issue.
I think you can simply retry the installation.

If you still have the issue, then please report the supervisor log.

**Comment by Exezz78** [comment]
Thanks a lot @mak-gitdev 

just did and can confirm Add-On loaded as expected.

Have a happy 2024!
