### ISSUE TITLE
Can't starting HA_enoceanmqtt addon

### ISSUE THREAD

**Issue by echaplet** [mak-gitdev/HA_enoceanmqtt#114]
### The problem

Hello, i have a problem to start the add on in Home Assistant with the last version of the addon (EnOcean MQTT (dev) 0.1.28-1)

I create the device file "enoceanmqtt.devices" in /config/

![image](https://github.com/mak-gitdev/HA_enoceanmqtt/assets/4331402/2cfe050d-3a51-44c7-a8fb-74654aa0016b)

Can you help me please ?
Thanks 

Eric

### What type of installation are you running?

Addon

### What version of HA_enoceanmqtt has the issue?

0.1.28-1

### What type of Home Assitant installation are you running?

Home Assistant OS

### Anything in the logs that might be useful to solve the issue? (Strongly recommended if applicable)

```txt
Preparing to start...
Retrieved devices file: /config/enoceanmqtt.devices
use_dev_name_in_entity is USER-DEFINED (false)
cat: can't open '/config/enoceanmqtt.devices': No such file or directory
```

**Comment by mak-gitdev** [comment]
Hi @echaplet,

From your screenshot, I can see that your device file is not located at `/config/enoceanmqtt.devices` but at `/homeassistant/config/enoceanmqtt.devices`.
That's why you got this error.

Simply set the `device_file` entry to the correct path and it should be OK.

**Comment by echaplet** [comment]
nop, it's not working

![image](https://github.com/mak-gitdev/HA_enoceanmqtt/assets/4331402/ea1da607-e281-4fae-a8cc-13c1a500b809)

**Comment by mak-gitdev** [comment]
@echaplet, 

Which version of HAOS are you using ?
Just saw that HA guys have made some changes in the way directories are mapped into the addon.

**Comment by echaplet** [comment]
Hello, the system information is :

![image](https://github.com/mak-gitdev/HA_enoceanmqtt/assets/4331402/764f5aa5-992c-4da6-ac01-6918fbf30b25)

![image](https://github.com/mak-gitdev/HA_enoceanmqtt/assets/4331402/9a0cb466-2e63-4abd-b005-9f4aa56b6474)

**Comment by mak-gitdev** [comment]
Hi @echaplet,

Set `device_file` to: `/config/config/enoceanmqtt.devices`.

**Comment by echaplet** [comment]
all right, it works , thanks ;-)
