### ISSUE TITLE
using an external broker

### ISSUE THREAD

**Issue by commentsonly** [mak-gitdev/HA_enoceanmqtt#27]
did as suggested, added
host: 192.168.1.xxx
port: 1883
user: username
pwd: password

and do get a 
Failed to save add-on configuration, not a valid value. Got ...... and so on......

any idea what's wrong? If it does matter .. dev channel version

**Comment by commentsonly** [comment]
oh found out myself 
On https://github.com/mak-gitdev/HA_enoceanmqtt at section "Home Assistant Addon Installation" in th esubsection "Configuration" is says:
host: localhost
port: 1883
user: my_user
pwd: my_password
but in the /addon-dev/run.sh
it looks for
host ... OK
port ... OK
username but user
password but pwd

this was the trick.
well part of it.
It also fails if one simply writed
host: 192.168.1.100
or
username: james
since it expects these to be within '' or ""
while when done so and accepted, next time viewed at the addon configuration the values do appear without quotes.

solved but not maked so so that Mark could validate and then close it.

**Comment by mak-gitdev** [comment]
Hi,

Thanks for spotting the issue when using an external broker.
I am surprised that it works for you when using `username` instead of `user` and `password` instead of `pwd`. Are you sure it works ?
In run.sh, you can see that `username` and `password` are used when retrieving internal broker parameters, which occurs when the `mqtt_broker` field is empty.'

When using an external broker, only port is required to be into single/double quote. You can try and confirm.

Furthermore, you can see in run.sh that I wanted to prevent the addon to start when all the MQTT broker parameters are not defined (`host`, `port`, `user` and `pwd`).
This is in fact the current issue as you have not defined `user` and `pwd` but the addon started.

**Comment by commentsonly** [comment]
Well it was a mixture of things I’d say.

 

First of all, I recently switched HA from a PI4 into an Intel thin client, whatever you would call it.

A small box which has the opportunity to not only come with USB, WiFi, BT but also with serial ports.

Got some of these, mostly i3 or i5 since if you are patient you get them for 100€ or ebay, and  ….. I must say I never owned anything better so far.

Fast, responsible, enough ports, small, silent. Everything one asks for if not into gaming where you need a full blown graphics card.

 

https://www.ebay.de/itm/144860679518?hash=item21ba5e8d5e:g:KT0AAOSwZMljQBQU <https://www.ebay.de/itm/144860679518?hash=item21ba5e8d5e:g:KT0AAOSwZMljQBQU&amdata=enc%3AAQAHAAAAoD0RWToomUMLbxEiGPdDjrrs3HC1eZTZYuCuW%2BUHDYcPvEdWE%2BpoZCuam2SYHNHMtCGlqj%2FDKoy4G%2BVdw9GqzmPJUzazCE5KZSlWLikUqSVqNdrBUgBn%2FZorREbeZSjs%2BLC4wtagOzzpZ5S9UKnIz%2Bx1e8hVYdYdSMEW%2BlZC4b0XmqwFwSWlaEPkgyWGUxKGHI3EbkIee6wk0IVFHnNZGsg%3D%7Ctkp%3ABk9SR-amnJWlYQ> &amdata=enc%3AAQAHAAAAoD0RWToomUMLbxEiGPdDjrrs3HC1eZTZYuCuW%2BUHDYcPvEdWE%2BpoZCuam2SYHNHMtCGlqj%2FDKoy4G%2BVdw9GqzmPJUzazCE5KZSlWLikUqSVqNdrBUgBn%2FZorREbeZSjs%2BLC4wtagOzzpZ5S9UKnIz%2Bx1e8hVYdYdSMEW%2BlZC4b0XmqwFwSWlaEPkgyWGUxKGHI3EbkIee6wk0IVFHnNZGsg%3D%7Ctkp%3ABk9SR-amnJWlYQ

 

And since Home Assistant runs lots smoother (my preferred test is to install the “ha_skyfield” since that puts more load onto HA but if you install 500 other things. 😊 If they runs smoothly the hardware is ok, if not, kick the hardware since you run into lags sooner or later.

 

As said I switched from the Pi. Grafana, node-red, mosquito and others still were located on the Pi only the Home Assistant was moved yet. (short in time)

But I wanted to get rid of that split, so first of all I installed Mosquitto on the Home Assistant machine. Then I merged/joined the MQTT servers so that the one from the PI got mirrored into the Home Assistant mosquito. Then I thought to give it a try with EMQX because it looked lots better.

And then the problems started to emerge.

I failed in getting EMQX running, better said it did run and I also managed to get some devices publish their topic on EMQX.

But I spent more but an hour in trying to let your addon accept EMQX broker instead of the Mosquitto.

All attempted resulted in not being privileged.

Home assistant did work and was granted access after having created a user with a pw and within EMQX I also added that user with admin rights.

But the addon simply failed and I got no idea why.

 

I then wanted to see if the addon can work with the old mosquito on the PI4 and that worked with username and password instead of user and pwd

 

If I do hate 1 thing from the linux world. These guys loving that system to life their complete life in fear. Burglars, Thiefs, hackers, …….

I got no time for this, and I do dislike certificates (the worst things invented) and all that SSL crap.

Yes I make use of such things when required, means for everything talking to the outside world. But if I have a mqtt broker on the same machine as an mqtt addon or a home assistant there’s no need to password nor security things. The only point to act in terms of security is the internet gateway switch which secures my home. Securing software within the house against each other is simply a waste of time and complicates the actual thing.

And .. as you know .. you can’t easily use mosquito without a user …. Strange. It should work out of the box, my viewpoint, and if doing so, throw a reminder that one should secure it. Nit the other way round .. define a user & password and end up with errors while being unsure if it’s an access issue or a general configuration issue.

And even with debug you don’t get logs in the form

Sent user = james using password = 123456 and access was rejected because of user unknown

Or rejected because password didn’t match.

You only get “access not given” which is as sensefull as “doesn’t work”

 

Found out another misery recently with the “\req” implementation.

I can easily switch my plugs with lights attached from the physical gira enocean button aswell as from the virtually defined one … as long as the relais I want to switch is defined within HA.

 

I can switch a FSB14 connected to the FAM14 using a real physical EnOcean butting, since an EnOcean telegram goes through the air.

But I can’t using these virtual buttons, nothing happens.

Means the virtual ones don’t act as being an EnOceon button but simply as a template button defined in HA.

 

I double checked that using my second Enocean stick plugged into my PC using software which does scan for EnOcean telegram floating through the air.

 

Something got broken or did it never work that way?

I see everything looks similar using an MQTT explorer, means besides the F60201 physical buttons there’s also the FFFFFF buttons.

And the payloads look next to identical.

But there’s no telegram sent somehow.

Any idea?

 

 

 

Von: mak-gitdev ***@***.***> 
Gesendet: Sonntag, 18. Dezember 2022 17:04
An: mak-gitdev/HA_enoceanmqtt ***@***.***>
Cc: commentsonly ***@***.***>; Author ***@***.***>
Betreff: Re: [mak-gitdev/HA_enoceanmqtt] using an external broker (Issue #27)

 

Hi,

Thanks for spotting the issue when using an external broker.
I am surprised that it works for you when using username instead of user and password instead of pwd. Are you sure it works ?
In run.sh, you can see that username and password are used when retrieving internal broker parameters, which occurs when the mqtt_broker field is empty.'

When using an external broker, only port is required to be into single/double quote. You can try and confirm.

Furthermore, you can see in run.sh that I wanted to prevent the addon to start when all the MQTT broker parameters are not defined (host, port, user and pwd).
This is in fact the current issue as you have not defined user and pwd but the addon started.

**Comment by mak-gitdev** [comment]
Fixed in the dev version.
Addon will not start unless all MQTT parameters are correctly set.
