### ISSUE TITLE
Addon not showing up in HA

### ISSUE THREAD

**Issue by holger-tangermann** [mak-gitdev/HA_enoceanmqtt#30]
When following the installation instructions (https://github.com/mak-gitdev/HA_enoceanmqtt-addon#installation), the add-on does not show up in HA.

**Comment by mak-gitdev** [comment]
Hi @holger-tangermann,

- Did you refresh the [addon page](https://my.home-assistant.io/redirect/supervisor_store/) after adding the repository ?
- Did the installation complete without error ?
- Which version did you install (dev or normal) ?

**Comment by holger-tangermann** [comment]
Hmmm .... after the HA restart for the new HA version this morning, the addon shows up normally.
