### ISSUE TITLE
could not install new version

### ISSUE THREAD

**Issue by Knobiwahn** [mak-gitdev/HA_enoceanmqtt#39]
installation stuck on error:

The command '/bin/ash -o pipefail -c apk add --no-cache python3 py3-pip git && python3 -m pip install --upgrade pip && pip3 install pyyaml && pip3 install tinydb && git clone https://github.com/embyt/enocean-mqtt.git && cd enocean-mqtt && python3 setup.py develop && cd .. && if [ -z "${BUILD_VERSION##*.*.*}" ]; then echo "Installing development version ${BUILD_VERSION%-*}" && git clone -b develop --single-branch --depth 1 https://github.com/mak-gitdev/HA_enoceanmqtt.git ; else echo "Installing Stable version ${BUILD_VERSION%-*}" && git clone -b master --single-branch --depth 1 https://github.com/mak-gitdev/HA_enoceanmqtt.git ; fi; cp -rf HA_enoceanmqtt/enoceanmqtt enocean-mqtt && cp -rf HA_enoceanmqtt/enocean/protocol/EEP.xml $(find / -path ./HA_enoceanmqtt -prune -o -name "EEP.xml" -print -quit 2>/dev/null) && rm -rf HA_enoceanmqtt' returned a non-zero code: 1

**Comment by mak-gitdev** [comment]
Hi @Knobiwahn,

How did you get this error ?
Which repository are you using ? It should be ha_enoceanmqtt-addon.
Which version are you trying to install ? Only dev version should be used for the moment.
What is your Home Assistant setup (hardware, installation type, etc.) ?

**Comment by Knobiwahn** [comment]
the error cames during installation ha_enoceanmqtt-addon
the deprecated version runs fine.
the development version runs, the error cames during installation of version 0.1 so the non development version.
Home Assistant runs on generic x86 intel with 8 gb ram.

**Comment by mak-gitdev** [comment]
You should install the dev version which is now version 0.1.24.
You installed the wrong one, 0.1 is the master version and is not maintained at the moment.
I think I will have to disable this one until it is OK to use it as well.

**Comment by mak-gitdev** [comment]
You should install the dev version which is now version 0.1.24.
You installed the wrong one, 0.1 is the master version and is not maintained at the moment.
I think I will have to disable this one until it is OK to use it as well.

**Comment by mak-gitdev** [comment]
Is everything working now ?
Can I close the issue ?

**Comment by Knobiwahn** [comment]
everithing works fine ...tnx alot
