### ISSUE TITLE
0.1.24 dev no way to get it running

### ISSUE THREAD

**Issue by commentsonly** [mak-gitdev/HA_enoceanmqtt#40]
Hi Marc as already informed ... 0.1.24 simply does nothing at all. Not a single device.
Should I have uninstalled the existing dev version first? The updated did run through without errors.
But I do miss an updated mappings and some information for the devices on how to use multiple virutal buttons.

I'm actually thinking if I should downgrade since 2 days without this addon is a real pain.
apart from my nodon plus sending energy reading none of all my buttons works since I upgraded.

**Comment by mak-gitdev** [comment]
Hi @commentsonly,

If you have a custom mapping.yaml file, before starting the new version, leave empty the configuration entry mapping_file or merge your modifications into the [latest version](https://github.com/mak-gitdev/HA_enoceanmqtt/blob/develop/enoceanmqtt/overlays/homeassistant/mapping.yaml), so that the latest added features are available.

Otherwise, you could run into an exception because your custom file is out of sync with the latest version and miss some features.

Regarding virtual buttons, have a look at this [wiki chapter](https://github.com/mak-gitdev/HA_enoceanmqtt/wiki/Usage#virtual-devices) for more details.

**Comment by commentsonly** [comment]
Dammit I must have missed a) the link to where the mapping file was located on your github
and also the note about the multiple virtual buttons.
And believe it or not I spend more but 10mins digging into every direction without any luck.
Perhaps such things should get placed on a more eye-catcher-alike location. 

And sure I got some custom  modifications of the mapping since my screens are way to small to allow selection boxed with terms such as "Query & Auto - Energy in kWh" 😄 I stripped these down to something shorter.

And I had to member to now correct my nodon plugs to D2-01-0E since being supported.

btw: any hint about the config entry EEP file? I never seen that before nor do I know what to do with it.

**Comment by commentsonly** [comment]
works ..... apart from the F6-10-00 hasn't got the common "delete" any more.
Nice one. thanks a lot for all your work done .... the mappings got quite massive already.

**Comment by commentsonly** [comment]
what I didn't get still is the following thing.
In the wiki it's explained about how to add virutal buttons in the devices.yaml. Looks similar as it was before apart from being to all more but one button.
But in the mappings,yaml I see some sort of selector. And I found nothing in the wiki about if something did change about how to make use the actual 'virtual' implementation. In the past you mentioned one could define button in the mqtt: config section but from the mapping.yaml it looks now lots more complexed. Hints appreciated

**Comment by mak-gitdev** [comment]
I updated the wiki. The `virtual` option was missing in the device declaration.

Before this version, devices were handled using there addresses. Hence, it was impossible to define more than one device with broadcast address (0xFFFFFFFF).
Now they are assigned a unique id consisting in a combination of their EEP, address and sender.

> In the past you mentioned one could define button in the mqtt: config section but from the mapping.yaml it looks now lots more complexed.

I finally used select. It is not complicated and I think it suits better.

Can I close the issue as everything is OK now ? Fill free to open a discussion.

**Comment by commentsonly** [comment]
Though you must have had something in mind with that select thing, otherwise you wouldn't have implemented it.
And I don't get it since I see to difference against the old implementation.

 I would have expected it to work similar like the D2-00-0E selection box when one selected Ws Wh and so on .... but sorry to say I don't see a selection box at all for the F6-02-01 virtual buttons.

It simply works the very same as it did before 0.1.24
I define a button in the mqtt: section
using a
command_topic in the form `enoceanmqtt/<virtual devicename from devices.yaml>/req`
with a
payload_press in the form `{"R1":<n>,"EB":<nr>, .......`

Everything works, but I doubt that you had this in mind since according to the mapping,yaml it's both a selector in D2-00-0E and F6-02-01 whereas the D2 offers this
![image](https://user-images.githubusercontent.com/35866491/219955864-4cd85eb2-18c9-4294-89ff-7193bc51a766.png)
a selection box whereas the F6 doesn't at all.

But you can close it, but I wished I did understand what would have been the way you now implemented it.

**Comment by mak-gitdev** [comment]
Did you add `virtual` like in  the wiki as updated ?

**Comment by commentsonly** [comment]
ups. .. one shouldn't copy an existing virual button so one got 2 .. and forget about adding the "virtual = 1" also to the existing one and yes my 2 virtual buttons do look differnt if looking in settings>Devices>MQTT
Issue solved ..... but I'll have to think about it .... looks as if now all my automations need some tuning since they won't work any longer.
