### ISSUE TITLE
HA_enoceanmqtt_addon Version 0.1.25 does not work

### ISSUE THREAD

**Issue by stefanhofmann2** [mak-gitdev/HA_enoceanmqtt#43]
Hello, because i can´t create an issue in repository HA_enoceanmqtt_addon(dev) i am reporting the problem here.
With the version 0.1.23 all devices are updating in the dashboard, but with the new version not. But you can see that there are messages in the logs.

**Comment by mak-gitdev** [comment]
Hi @stefanhofmann2,

Could you share the enoceanmqtt.log file ?

**Comment by mak-gitdev** [comment]
@stefanhofmann2,

Is this issue still relevant ?
