### ISSUE TITLE
Update of Add-on Failed

### ISSUE THREAD

**Issue by holger-tangermann** [mak-gitdev/HA_enoceanmqtt#52]
Updating the addon via HA standard frontend failed. 
![image](https://user-images.githubusercontent.com/76705846/221370349-f7af2b44-4c22-4f33-bc15-ab9c8db590a8.png)
Please let me know, if you need any additional information.

**Comment by mak-gitdev** [comment]
Hi @holger-tangermann,

Uninstall this version and install the `dev` version.

**Comment by mak-gitdev** [comment]
@holger-tangermann, please close the issue if it is solved. Thanks

**Comment by holger-tangermann** [comment]
I moved to Dev branch and it is working for me. 

However, for some devices the entities got duplicated now. 
![image](https://user-images.githubusercontent.com/76705846/221420751-bd91722e-e4de-4cbc-bd64-1ef72a02798e.png)

**Comment by mak-gitdev** [comment]
Ok,

- Stop the addon.
- Remove or comment (line starting with #) all your devices from your device file.
- Start the addon, it will remove all entities.
- Stop the addon.
- Add or uncomment all your devices from your device file.
- Start the addon, everything should be OK now.

**Comment by holger-tangermann** [comment]
top! That worked beautyfully!
