### ISSUE TITLE
Missing files after Standalone Installation

### ISSUE THREAD

**Issue by Olivier-CHAPUIS** [mak-gitdev/HA_enoceanmqtt#66]
Hi Mark, i am new in HA ( migration from Jeedom) and i have some ENOCEAN equipment ( AVIDSEN 0D-01-0C ). My HA installation is fully new and by this way i have jumped the migration step. When i start the module ( after completed the configuration forms) i have error messages  ( see attached file)

I am verified the HA tree and i don't find any directory data or app , ... and by this way the requested files.
Could you inform me if my installation process is wrong? How i could solve it?
Thanks

This HA installation is done on a VM located on a freebox Delta

[enoceanmqtt.log](https://github.com/mak-gitdev/HA_enoceanmqtt/files/11522015/enoceanmqtt.log)
[error-message.txt](https://github.com/mak-gitdev/HA_enoceanmqtt/files/11522016/error-message.txt)

**Comment by mak-gitdev** [comment]
Hi @Olivier-CHAPUIS,

From the logs you shared, it seems that you are using the addon, not the standalone installation.
Could you please describe in details what you've done so that I can help you.

**Comment by Olivier-CHAPUIS** [comment]
Hi,

Sorry, i had sent to you a wrong information. I had installed an ADDON installation , as confirmed by the snapshot. I had choosen this installation type as all is included inside only one VM.

To list the action done:


  *   Installation of HA
  *   Installation of module HACS, File editor, Samba, Duck DNS
  *   Integration of Conbee II and ZWAVE

-          Installation of EnOcean to MQTT Bridge (development version) en mode ADDON and NEW installation ( jump the Upgrade paragraph)

  *   The MQTT intégration was certainly done by HA as I don't did anything on the subject
  *   I configure the parameter
  *   I have created the directory \config\enoceanmqtt where I drop the different files founded by reading your installation procedure

I hope I have listed all my actions.

Thanks for your help


Olivier CHAPUIS
***@***.***

De : mak-gitdev ***@***.***>
Envoyé : dimanche 21 mai 2023 19:41
À : mak-gitdev/HA_enoceanmqtt ***@***.***>
Cc : Olivier-CHAPUIS ***@***.***>; Mention ***@***.***>
Objet : Re: [mak-gitdev/HA_enoceanmqtt] Missing files after Standalone Installation (Issue #66)


Hi @Olivier-CHAPUIS<https://github.com/Olivier-CHAPUIS>,

From the logs you shared, it seems that you are using the addon, not the standalone installation.
Could you please describe in details what you've done so that I can help you.

-

**Comment by mak-gitdev** [comment]
From error_message.txt, I don't understand this line:
```
Retrieved devices file: /config/enoceanmqtt/device_manager.py
```
`device_manager.py` has nothing to do there.

You just have to follow the instructions in the [wiki](https://github.com/mak-gitdev/HA_enoceanmqtt/wiki/Home-Assistant-Addon#configuration).
Could you also share your addon configuration. I think there are some mistakes there.

**Comment by Olivier-CHAPUIS** [comment]
Hi, Thanks for your help.


After retreive the file: /config/enoceanmqtt/device_manager.py and replaced by the file: /config/enoceanmqtt/enoceanmqtt.devices.sample and verified all the hexadecimal address of each Enocean modules, the module starts with OK status.



I have started the MQTT integration, and it has found the 4 Avidsen Enocean modules.



Now I need to find how to send command to these modules to change their status.

Thanks again
Olivier CHAPUIS
***@***.***

De : mak-gitdev ***@***.***>
Envoyé : dimanche 21 mai 2023 23:32
À : mak-gitdev/HA_enoceanmqtt ***@***.***>
Cc : Olivier-CHAPUIS ***@***.***>; Mention ***@***.***>
Objet : Re: [mak-gitdev/HA_enoceanmqtt] Missing files after Standalone Installation (Issue #66)


From error_message.txt, I don't understand this line:

Retrieved devices file: /config/enoceanmqtt/device_manager.py

device_manager.py has nothing to do there.

You just have to follow the instructions in the wiki<https://github.com/mak-gitdev/HA_enoceanmqtt/wiki/Home-Assistant-Addon#configuration>.
Could you also share your addon configuration. I think there are some mistakes there.

-

**Comment by Olivier-CHAPUIS** [comment]
Hi, Thanks for your help. 

After remove the file: /config/enoceanmqtt/device_manager.py and copied the file: /config/enoceanmqtt/enoceanmqtt.devices.sample and verified all the hexadecimal address of each Enocean modules, the module starts with OK status.

I have started the MQTT integration, and it has found the 4 Avidsen Enocean modules.
