### ISSUE TITLE
hmmm works similar to all my previous attempts with enocean in total by 0%

### ISSUE THREAD

**Issue by commentsonly** [mak-gitdev/HA_enoceanmqtt#7]
got some buttons .......
the EnOcan MQTT says
unknown sensor: FE:E5:0F:0C and since that's 4 items against all your documentation I've seen I don't have the slighest idea about what to do.
Any idea?
Once I manged to get them work somehow inside node-red using an Enocean integtration but I never came close to the point where even this worked reliable. Enocean is still the biggest miracle I ever across in my life. It's the opposite of WiFi .... which simply always works no matter if one's 100% noob. Enocean in return is something where you could invest weeks without gettting the smallest step further. That's my experience so far, while I still like the idea behind Enocean.

nevertheless the EnOcean MQTT HA integration makes things lots easier.

**Comment by mak-gitdev** [comment]
Hi,

I didn't get everything.
What device are you trying to integrate ?
Have you define it in your device file ?
You will need the EEP and the address of your device.
Your address seems to be 0xFEE50F0C.
How did you install HA_enoceanmqtt ?

**Comment by commentsonly** [comment]
ups 0xFEE50F9C is correct, my fault, the bloddy GIRA 4-way button got a sticker which is by now in white foreground with white background so that the printed number gone. Thanks to gira not being able to use water resistnant color for printing.
The EEP seems to be F6 02 01 don't ask where I got this from but I found in my old node-red flows.

Installation: mosquitto + the repositoy addon through add-ons.

I see the first difference now in the EnOcean MQTT logs window, where is says "Device enoceanmqtt/button1 [@FEE50F9C / EEP: F6-02-01) added o the device database

any idea about the next step?

**Comment by mak-gitdev** [comment]
Ok. Everything is ok then.

Just go to `settings`, then `devices and services`, then click on `devices` under the MQTT integration.
You should then see a device whose name is prefixed by `e2m_`.
Click on it, click on the your rocker buttons and that's it.
You have 5 entities. 1 per button and 1 when any button is pressed.

**Comment by commentsonly** [comment]
No ... yes I see the "e2m_button 1"
But I only have 1 entity 1 per 4 buttons better said 1 entity 1 button and it doesn't matter which one I press. :-)

**Comment by mak-gitdev** [comment]
Could you share a screenshot of `e2m_button1` device page ?

**Comment by commentsonly** [comment]
As said ... 1 button on this screen
![shot1](https://user-images.githubusercontent.com/35866491/202841501-3b22e16e-c6a9-42a6-83a7-37b9b1e54ac8.png)

but everything there when I had a look in here
Developper Tools > States (filtering for e2m
![shot2](https://user-images.githubusercontent.com/35866491/202841514-5ba9e998-4e68-44ca-93f9-e6381aa31a46.png)

5 binary sensor entries
binary_sensor.e2m_button_1_ai_pressed
binary_sensor.e2m_button_1_ao_pressed
binary_sensor.e2m_button_1_bi_pressed
binary_sensor.e2m_button_1_bo_pressed
binary_sensor.e2m_button_1_pressed
and 2button entries
button.e2m_button_1_delete
button.e2m_button_1_rssi

but somethings still missing on the  Settings>AddOn>EnOcean.MQTT tile. If you open this you see everything but no "donate" nor "buy-me-a-coffee" button ... but ok it's alpha stage, you can easily add one for sure.

thanks a lot ..... this addon made turns Enocean into something more sensefull but an advanced technology. Hopefully it survives the emerging Matter/Thread thingy since when it comes to the pure technology it's way ahead.

**Comment by mak-gitdev** [comment]
Ok I see.
Refresh the page of e2m_button_1, and please tell me if other entities appeared.
But most of all, you must avoid spaces in the device name. This is not handled.
Rename your device, that will for sure fix this that

**Comment by commentsonly** [comment]
yepp .. renaming (no spaces) and F5 solved the trick. Now 5 buttons are shown.
Typical windows user problem, the advantage being able to make use of the space key on the keybord to make things more readable.
Any idea what's mqttmapping.yaml is for? As far as I can see I won't need that at all.

**Comment by mak-gitdev** [comment]
Great that it's fully ok now.

As for mapping.yaml, it is a kind of "black magic" that maps an EEP to Home Assistant entities. It is of paramount importance.

I am also a huge fan of the EnOcean protocol.
As I was frustrated with the initial support in HA, I decided to try make something based on MQTT, especially enoceanmqtt from @romor.
It is still in early phase, even if it is working on my side for up to 6+ months. I try to make continuous improvements.
Hope it will help HA users rediscover this beautiful protocol.

By the way, do not hesitate to open a discussion if you want me to add support for a device not yet supported.
I will try do it when time is available.
