### ISSUE TITLE
HA warning: "Discovered entities with a name that starts with the device name"

### ISSUE THREAD

**Issue by hlinden** [mak-gitdev/HA_enoceanmqtt#77]
### The problem

Currently Home Assisant warns:

> 
> Discovered entities with a name that starts with the device name
> 
> Some MQTT entities have an entity name that starts with the device name. This is not expected. To avoid a duplicate name the device name prefix is stripped of the entity name as a work-a-round. Please inform the maintainer of the software application that supplies the affected entities to fix this issue.
> 
> List of affected entities:
> 
> [...List of all EnOcean devices.]

![ha_warning](https://github.com/mak-gitdev/HA_enoceanmqtt/assets/4718458/6903aeed-cab7-41c8-9648-7b2447e3890f)

What support, information or help can I provide to help fix this before the release of 2024.2.0.?

### What type of installation are you running?

Addon

### What version of HA_enoceanmqtt has the issue?

0.1.26

### What type of Home Assitant installation are you running?

Home Assistant OS

**Comment by mak-gitdev** [comment]
Hi @hlinden,

I was about to create an issue to indicate that I am aware of that but you were faster than me :).

So yes I am aware of this warning. It will be fixed with the next release.
You can also have a look at #76.

Thanks :+1:

**Comment by mak-gitdev** [comment]
https://github.com/users/mak-gitdev/projects/1?pane=issue&itemId=35566401

**Comment by mak-gitdev** [comment]
Fixed by commit [0d0a4cd](https://github.com/mak-gitdev/HA_enoceanmqtt/commit/0d0a4cdb3d74b191feb0cc9169e11f10243d1ec9)
