### ISSUE TITLE
Missing device_file, mapping_file and eep_file after Installation 

### ISSUE THREAD

**Issue by memooox3** [mak-gitdev/HA_enoceanmqtt#81]
### The problem

Hi,

I installed the addon and there are the above mentioned Files Missing, so I can't configurate the Addon. Iam not able to start the Addon without these Files.

### What type of installation are you running?

Addon

### What version of HA_enoceanmqtt has the issue?

0.1.26

### What type of Home Assitant installation are you running?

Home Assistant OS

### Anything in the logs that might be useful to solve the issue? (Strongly recommended if applicable)

```txt
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[12:32:29] FATAL: 
[12:32:29] FATAL: A required add-on configuration option is missing!
[12:32:29] FATAL: 
[12:32:29] FATAL: Please set a value for the 'device_file' option.
[12:32:29] FATAL: 
[12:32:29] FATAL: If unsure, check the add-on manual for more information.
[12:32:29] FATAL: 
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by mak-gitdev** [comment]
Hi @memooox3,

In the configuration tab of the addon, for the entry `device_file`, you should indicate the path to your enoceanmqtt.devices file.
The fatal error in the addon log indicate that this entry is empty.
The addon can't start without that.

More details in the [wiki](https://github.com/mak-gitdev/HA_enoceanmqtt/wiki/Home-Assistant-Addon#configuration)

**Comment by memooox3** [comment]
Hi @mak-gitdev ,

thanks for the fast reply.
After the initial Installation all three files are not automatically installed. 
In the /config path there is either the enoceanmqtt.devices nor an mapping.yaml file. So tomorrow I will search the files from the code basis here in GitHub and will copy it to my system.

So the issue is that it is, at the moment, not possible to install and configure the addon easily.

**Comment by mak-gitdev** [comment]
Hi @memooox3,

As explained in the wiki, the enoceanmqtt.devices has to be created by the user.
An example is given by the [enoceanmqtt.devices.sample](https://github.com/mak-gitdev/HA_enoceanmqtt-addon/blob/master/addon-dev/enoceanmqtt.devices.sample) file.
I will add a link to this file in the wiki to make it easily accessible.

Regarding entries `mapping_file` and `eep_file`, they are not required and are only to be used when the user want advanced features such as adding support for new devices or customize existing supported devices.
Please have a look at this [link](https://github.com/mak-gitdev/HA_enoceanmqtt/wiki/Examples#using-custom-mappingyaml-andor-eepxml-files) for more details.

Please feel free to share any ideas to make all that clearer.
Thanks.

**Comment by mak-gitdev** [comment]
@memooox3,

Is everything OK now or are you still unable to run the addon ?

**Comment by memooox3** [comment]
Yes, the Addon is now running.
Thank you for your help.
I read in a German community, that the files were automatically created in an earlier version, so I opened this issue.
But you clarified this step with adding the link to the wiki. Thank you for your help!
