### ISSUE TITLE
Problem with Standalone-Installation

### ISSUE THREAD

**Issue by StickyOrangE** [mak-gitdev/HA_enoceanmqtt#92]
### The problem

Hello,

I have a problem with the Standalone-Installation of HA_enoceanmqtt.
I run it in a LXC-Container in Proxmox with Ubuntu 23.04.
Its a privileged Container, otherwise USB will not work correctly.

The Installation with the Script runs smoothly i think:
[https://pastebin.com/RBAZ4Y6z](https://pastebin.com/RBAZ4Y6z)

The Script is in "/etc/enoceanmqtt", so the Installation-Path is "/etc/enoceanmqtt/enocean-mqtt".
I also put the "enoceanmqtt.conf"-File in "/etc" and changed it for my desires:
[https://pastebin.com/PnWvsgS7](https://pastebin.com/PnWvsgS7)

Now if i want to run "enoceanmqtt" in the console i get the error "Command not found"

Did i do something wrong?
Im not that familiar with the terminal yet.

Thanks in advance!

### What type of installation are you running?

Standalone

### What type of Home Assitant installation are you running?

Home Assistant OS

**Comment by mak-gitdev** [comment]
Hi @StickyOrangE,

You don't need to be root to install it and I strongly discourage installing it with the root user.
Try reinstall it in a directory in the home directory of your non-root user account .

As you said to be not very familiar with the terminal and if your use-case doesn't require a standalone installation, you may consider the [Addon installation](https://github.com/mak-gitdev/HA_enoceanmqtt/wiki/Home-Assistant-Addon) as it is the simplest one.

**Comment by mak-gitdev** [comment]
@StickyOrangE, 

Anything new ?
